// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: answers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT id, submission_id, question_id, raw_answer, created_at, updated_at FROM answers WHERE id = $1
`

// GetAnswerByID
//
//	SELECT id, submission_id, question_id, raw_answer, created_at, updated_at FROM answers WHERE id = $1
func (q *Queries) GetAnswerByID(ctx context.Context, id uuid.UUID) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByID, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.RawAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswersBySubmission = `-- name: ListAnswersBySubmission :many
SELECT id, submission_id, question_id, raw_answer, created_at, updated_at FROM answers WHERE submission_id = $1 ORDER BY created_at
`

// ListAnswersBySubmission
//
//	SELECT id, submission_id, question_id, raw_answer, created_at, updated_at FROM answers WHERE submission_id = $1 ORDER BY created_at
func (q *Queries) ListAnswersBySubmission(ctx context.Context, submissionID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.QuestionID,
			&i.RawAnswer,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswer = `-- name: UpdateAnswer :one
UPDATE answers SET raw_answer = $2, updated_at = now() WHERE id = $1
RETURNING id, submission_id, question_id, raw_answer, created_at, updated_at
`

// UpdateAnswer
//
//	UPDATE answers SET raw_answer = $2, updated_at = now() WHERE id = $1
//	RETURNING id, submission_id, question_id, raw_answer, created_at, updated_at
func (q *Queries) UpdateAnswer(ctx context.Context, iD uuid.UUID, rawAnswer string) (Answer, error) {
	row := q.db.QueryRow(ctx, updateAnswer, iD, rawAnswer)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.RawAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAnswer = `-- name: UpsertAnswer :one
INSERT INTO answers (submission_id, question_id, raw_answer)
VALUES ($1, $2, $3)
ON CONFLICT (submission_id, question_id) DO UPDATE SET raw_answer = EXCLUDED.raw_answer, updated_at = now()
RETURNING id, submission_id, question_id, raw_answer, created_at, updated_at
`

type UpsertAnswerParams struct {
	SubmissionID uuid.UUID
	QuestionID   uuid.UUID
	RawAnswer    string
}

// UpsertAnswer
//
//	INSERT INTO answers (submission_id, question_id, raw_answer)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (submission_id, question_id) DO UPDATE SET raw_answer = EXCLUDED.raw_answer, updated_at = now()
//	RETURNING id, submission_id, question_id, raw_answer, created_at, updated_at
func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, upsertAnswer, arg.SubmissionID, arg.QuestionID, arg.RawAnswer)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.RawAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
