// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, kind, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    uuid.UUID
	Kind      string
	TokenHash string
	ExpiresAt time.Time
}

// CreateAuthToken
//
//	INSERT INTO auth_tokens (user_id, kind, token_hash, expires_at)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// CreateRefreshToken
//
//	INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, verified, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
	Role         string
}

// CreateUser
//
//	INSERT INTO users (email, password_hash, name, role)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, email, password_hash, name, role, verified, created_at, updated_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAuthToken = `-- name: GetLatestAuthToken :one
SELECT id, user_id, kind, token_hash, expires_at, used_at, created_at FROM auth_tokens
WHERE user_id = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

// GetLatestAuthToken
//
//	SELECT id, user_id, kind, token_hash, expires_at, used_at, created_at FROM auth_tokens
//	WHERE user_id = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestAuthToken(ctx context.Context, userID uuid.UUID, kind string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getLatestAuthToken, userID, kind)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

// GetRefreshToken
//
//	SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens
//	WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, verified, created_at, updated_at FROM users WHERE email = $1
`

// GetUserByEmail
//
//	SELECT id, email, password_hash, name, role, verified, created_at, updated_at FROM users WHERE email = $1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, verified, created_at, updated_at FROM users WHERE id = $1
`

// GetUserByID
//
//	SELECT id, email, password_hash, name, role, verified, created_at, updated_at FROM users WHERE id = $1
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens SET used_at = now() WHERE id = $1
`

// MarkAuthTokenUsed
//
//	UPDATE auth_tokens SET used_at = now() WHERE id = $1
func (q *Queries) MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuthTokenUsed, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

// RevokeRefreshToken
//
//	UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

// UpdateUserPassword
//
//	UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
func (q *Queries) UpdateUserPassword(ctx context.Context, iD uuid.UUID, passwordHash string) error {
	_, err := q.db.Exec(ctx, updateUserPassword, iD, passwordHash)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET verified = true, updated_at = now() WHERE id = $1
`

// VerifyUser
//
//	UPDATE users SET verified = true, updated_at = now() WHERE id = $1
func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
