// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: class_subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkAddClassSubjects = `-- name: BulkAddClassSubjects :exec
INSERT INTO class_subjects (class_id, subject_id)
SELECT $1, s FROM unnest($2::uuid[]) AS s
ON CONFLICT (class_id, subject_id) DO NOTHING
`

// One statement, so the whole selection lands atomically. Already-selected
// Subjects are left alone rather than erroring.
//
//	INSERT INTO class_subjects (class_id, subject_id)
//	SELECT $1, s FROM unnest($2::uuid[]) AS s
//	ON CONFLICT (class_id, subject_id) DO NOTHING
func (q *Queries) BulkAddClassSubjects(ctx context.Context, classID uuid.UUID, subjectIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, bulkAddClassSubjects, classID, subjectIds)
	return err
}

const countClassSubjectsBySubject = `-- name: CountClassSubjectsBySubject :one
SELECT count(*) FROM class_subjects WHERE subject_id = $1
`

// CountClassSubjectsBySubject
//
//	SELECT count(*) FROM class_subjects WHERE subject_id = $1
func (q *Queries) CountClassSubjectsBySubject(ctx context.Context, subjectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClassSubjectsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSubjectsByClass = `-- name: ListSubjectsByClass :many
SELECT s.id, s.name, s.owner_id, s.created_at FROM subjects s
JOIN class_subjects cs ON cs.subject_id = s.id
WHERE cs.class_id = $1
ORDER BY s.name
`

// ListSubjectsByClass
//
//	SELECT s.id, s.name, s.owner_id, s.created_at FROM subjects s
//	JOIN class_subjects cs ON cs.subject_id = s.id
//	WHERE cs.class_id = $1
//	ORDER BY s.name
func (q *Queries) ListSubjectsByClass(ctx context.Context, classID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassSubject = `-- name: RemoveClassSubject :exec
DELETE FROM class_subjects WHERE class_id = $1 AND subject_id = $2
`

// RemoveClassSubject
//
//	DELETE FROM class_subjects WHERE class_id = $1 AND subject_id = $2
func (q *Queries) RemoveClassSubject(ctx context.Context, classID uuid.UUID, subjectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeClassSubject, classID, subjectID)
	return err
}
