// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addClassSubject = `-- name: AddClassSubject :one
INSERT INTO class_subjects (class_id, subject_id)
VALUES ($1, $2)
ON CONFLICT (class_id, subject_id) DO UPDATE SET class_id = EXCLUDED.class_id
RETURNING class_id, subject_id, created_at
`

// AddClassSubject
//
//	INSERT INTO class_subjects (class_id, subject_id)
//	VALUES ($1, $2)
//	ON CONFLICT (class_id, subject_id) DO UPDATE SET class_id = EXCLUDED.class_id
//	RETURNING class_id, subject_id, created_at
func (q *Queries) AddClassSubject(ctx context.Context, classID uuid.UUID, subjectID uuid.UUID) (ClassSubject, error) {
	row := q.db.QueryRow(ctx, addClassSubject, classID, subjectID)
	var i ClassSubject
	err := row.Scan(&i.ClassID, &i.SubjectID, &i.CreatedAt)
	return i, err
}

const listSubjectsByClass = `-- name: ListSubjectsByClass :many
SELECT s.id, s.name, s.owner_id, s.created_at FROM subjects s
JOIN class_subjects cs ON cs.subject_id = s.id
WHERE cs.class_id = $1
ORDER BY s.name
`

// ListSubjectsByClass
//
//	SELECT s.id, s.name, s.owner_id, s.created_at FROM subjects s
//	JOIN class_subjects cs ON cs.subject_id = s.id
//	WHERE cs.class_id = $1
//	ORDER BY s.name
func (q *Queries) ListSubjectsByClass(ctx context.Context, classID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassSubject = `-- name: RemoveClassSubject :exec
DELETE FROM class_subjects WHERE class_id = $1 AND subject_id = $2
`

// RemoveClassSubject
//
//	DELETE FROM class_subjects WHERE class_id = $1 AND subject_id = $2
func (q *Queries) RemoveClassSubject(ctx context.Context, classID uuid.UUID, subjectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeClassSubject, classID, subjectID)
	return err
}
