// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at, updated_at
`

// CreateClass
//
//	INSERT INTO classes (name, created_by)
//	VALUES ($1, $2)
//	RETURNING id, name, created_by, created_at, updated_at
func (q *Queries) CreateClass(ctx context.Context, name string, createdBy uuid.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, createClass, name, createdBy)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes WHERE id = $1
`

// DeleteClass
//
//	DELETE FROM classes WHERE id = $1
func (q *Queries) DeleteClass(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, name, created_by, created_at, updated_at FROM classes WHERE id = $1
`

// GetClassByID
//
//	SELECT id, name, created_by, created_at, updated_at FROM classes WHERE id = $1
func (q *Queries) GetClassByID(ctx context.Context, id uuid.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassesByOwner = `-- name: ListClassesByOwner :many
SELECT id, name, created_by, created_at, updated_at FROM classes WHERE created_by = $1 ORDER BY created_at DESC
`

// ListClassesByOwner
//
//	SELECT id, name, created_by, created_at, updated_at FROM classes WHERE created_by = $1 ORDER BY created_at DESC
func (q *Queries) ListClassesByOwner(ctx context.Context, createdBy uuid.UUID) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByOwner, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes SET name = $2, updated_at = now() WHERE id = $1
RETURNING id, name, created_by, created_at, updated_at
`

// UpdateClass
//
//	UPDATE classes SET name = $2, updated_at = now() WHERE id = $1
//	RETURNING id, name, created_by, created_at, updated_at
func (q *Queries) UpdateClass(ctx context.Context, iD uuid.UUID, name string) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass, iD, name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
