// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evaluations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvaluation = `-- name: CreateEvaluation :one
INSERT INTO evaluations (evaluation_attempt_id, raw_score, marks, feedback)
VALUES ($1, $2, $3, $4)
RETURNING id, evaluation_attempt_id, raw_score, marks, feedback, breakdown, created_at
`

type CreateEvaluationParams struct {
	EvaluationAttemptID uuid.UUID
	RawScore            pgtype.Numeric
	Marks               pgtype.Numeric
	Feedback            string
}

// CreateEvaluation
//
//	INSERT INTO evaluations (evaluation_attempt_id, raw_score, marks, feedback)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, evaluation_attempt_id, raw_score, marks, feedback, breakdown, created_at
func (q *Queries) CreateEvaluation(ctx context.Context, arg CreateEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, createEvaluation,
		arg.EvaluationAttemptID,
		arg.RawScore,
		arg.Marks,
		arg.Feedback,
	)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.EvaluationAttemptID,
		&i.RawScore,
		&i.Marks,
		&i.Feedback,
		&i.Breakdown,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationByAttemptID = `-- name: GetEvaluationByAttemptID :one
SELECT id, evaluation_attempt_id, raw_score, marks, feedback, breakdown, created_at FROM evaluations WHERE evaluation_attempt_id = $1
`

// GetEvaluationByAttemptID
//
//	SELECT id, evaluation_attempt_id, raw_score, marks, feedback, breakdown, created_at FROM evaluations WHERE evaluation_attempt_id = $1
func (q *Queries) GetEvaluationByAttemptID(ctx context.Context, evaluationAttemptID uuid.UUID) (Evaluation, error) {
	row := q.db.QueryRow(ctx, getEvaluationByAttemptID, evaluationAttemptID)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.EvaluationAttemptID,
		&i.RawScore,
		&i.Marks,
		&i.Feedback,
		&i.Breakdown,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestScoringEvaluationByAnswer = `-- name: GetLatestScoringEvaluationByAnswer :one
SELECT evaluations.id, evaluations.evaluation_attempt_id, evaluations.raw_score, evaluations.marks, evaluations.feedback, evaluations.breakdown, evaluations.created_at
FROM evaluations
JOIN evaluation_attempts ON evaluation_attempts.id = evaluations.evaluation_attempt_id
WHERE evaluation_attempts.answer_id = $1
  AND evaluation_attempts.purpose = 'scoring'
ORDER BY evaluations.created_at DESC
LIMIT 1
`

// GetLatestScoringEvaluationByAnswer
//
//	SELECT evaluations.id, evaluations.evaluation_attempt_id, evaluations.raw_score, evaluations.marks, evaluations.feedback, evaluations.breakdown, evaluations.created_at
//	FROM evaluations
//	JOIN evaluation_attempts ON evaluation_attempts.id = evaluations.evaluation_attempt_id
//	WHERE evaluation_attempts.answer_id = $1
//	  AND evaluation_attempts.purpose = 'scoring'
//	ORDER BY evaluations.created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestScoringEvaluationByAnswer(ctx context.Context, answerID uuid.UUID) (Evaluation, error) {
	row := q.db.QueryRow(ctx, getLatestScoringEvaluationByAnswer, answerID)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.EvaluationAttemptID,
		&i.RawScore,
		&i.Marks,
		&i.Feedback,
		&i.Breakdown,
		&i.CreatedAt,
	)
	return i, err
}
