// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exams.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createExam = `-- name: CreateExam :one
INSERT INTO exams (class_id, label)
VALUES ($1, $2)
RETURNING id, class_id, label, created_at, updated_at
`

// CreateExam
//
//	INSERT INTO exams (class_id, label)
//	VALUES ($1, $2)
//	RETURNING id, class_id, label, created_at, updated_at
func (q *Queries) CreateExam(ctx context.Context, classID uuid.UUID, label string) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam, classID, label)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExamByID = `-- name: GetExamByID :one
SELECT id, class_id, label, created_at, updated_at FROM exams WHERE id = $1
`

// GetExamByID
//
//	SELECT id, class_id, label, created_at, updated_at FROM exams WHERE id = $1
func (q *Queries) GetExamByID(ctx context.Context, id uuid.UUID) (Exam, error) {
	row := q.db.QueryRow(ctx, getExamByID, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamsByClass = `-- name: ListExamsByClass :many
SELECT id, class_id, label, created_at, updated_at FROM exams WHERE class_id = $1 ORDER BY created_at DESC
`

// ListExamsByClass
//
//	SELECT id, class_id, label, created_at, updated_at FROM exams WHERE class_id = $1 ORDER BY created_at DESC
func (q *Queries) ListExamsByClass(ctx context.Context, classID uuid.UUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
