// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exam_subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addExamSubject = `-- name: AddExamSubject :one
INSERT INTO exam_subjects (exam_id, subject_id)
VALUES ($1, $2)
ON CONFLICT (exam_id, subject_id) DO UPDATE SET exam_id = EXCLUDED.exam_id
RETURNING id, exam_id, subject_id, created_at
`

// AddExamSubject
//
//	INSERT INTO exam_subjects (exam_id, subject_id)
//	VALUES ($1, $2)
//	ON CONFLICT (exam_id, subject_id) DO UPDATE SET exam_id = EXCLUDED.exam_id
//	RETURNING id, exam_id, subject_id, created_at
func (q *Queries) AddExamSubject(ctx context.Context, examID uuid.UUID, subjectID uuid.UUID) (ExamSubject, error) {
	row := q.db.QueryRow(ctx, addExamSubject, examID, subjectID)
	var i ExamSubject
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.SubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getExamSubjectByID = `-- name: GetExamSubjectByID :one
SELECT id, exam_id, subject_id, created_at FROM exam_subjects WHERE id = $1
`

// GetExamSubjectByID
//
//	SELECT id, exam_id, subject_id, created_at FROM exam_subjects WHERE id = $1
func (q *Queries) GetExamSubjectByID(ctx context.Context, id uuid.UUID) (ExamSubject, error) {
	row := q.db.QueryRow(ctx, getExamSubjectByID, id)
	var i ExamSubject
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.SubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const listExamSubjectsByExam = `-- name: ListExamSubjectsByExam :many
SELECT id, exam_id, subject_id, created_at FROM exam_subjects WHERE exam_id = $1 ORDER BY created_at
`

// ListExamSubjectsByExam
//
//	SELECT id, exam_id, subject_id, created_at FROM exam_subjects WHERE exam_id = $1 ORDER BY created_at
func (q *Queries) ListExamSubjectsByExam(ctx context.Context, examID uuid.UUID) ([]ExamSubject, error) {
	rows, err := q.db.Query(ctx, listExamSubjectsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamSubject
	for rows.Next() {
		var i ExamSubject
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.SubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
