// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_calls.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLLMCall = `-- name: CreateLLMCall :one
INSERT INTO llm_calls (
    evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out,
    cached_tokens, thinking_tokens, latency_ms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out, cached_tokens, thinking_tokens, latency_ms, created_at
`

type CreateLLMCallParams struct {
	EvaluationAttemptID uuid.UUID
	CorrelationID       uuid.UUID
	Model               string
	TokensIn            int32
	TokensOut           int32
	CachedTokens        *int32
	ThinkingTokens      *int32
	LatencyMs           int32
}

// CreateLLMCall
//
//	INSERT INTO llm_calls (
//	    evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out,
//	    cached_tokens, thinking_tokens, latency_ms
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out, cached_tokens, thinking_tokens, latency_ms, created_at
func (q *Queries) CreateLLMCall(ctx context.Context, arg CreateLLMCallParams) (LlmCall, error) {
	row := q.db.QueryRow(ctx, createLLMCall,
		arg.EvaluationAttemptID,
		arg.CorrelationID,
		arg.Model,
		arg.TokensIn,
		arg.TokensOut,
		arg.CachedTokens,
		arg.ThinkingTokens,
		arg.LatencyMs,
	)
	var i LlmCall
	err := row.Scan(
		&i.ID,
		&i.EvaluationAttemptID,
		&i.CorrelationID,
		&i.Model,
		&i.TokensIn,
		&i.TokensOut,
		&i.CachedTokens,
		&i.ThinkingTokens,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const listLLMCallsByAttempt = `-- name: ListLLMCallsByAttempt :many
SELECT id, evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out, cached_tokens, thinking_tokens, latency_ms, created_at FROM llm_calls WHERE evaluation_attempt_id = $1 ORDER BY created_at
`

// ListLLMCallsByAttempt
//
//	SELECT id, evaluation_attempt_id, correlation_id, model, tokens_in, tokens_out, cached_tokens, thinking_tokens, latency_ms, created_at FROM llm_calls WHERE evaluation_attempt_id = $1 ORDER BY created_at
func (q *Queries) ListLLMCallsByAttempt(ctx context.Context, evaluationAttemptID uuid.UUID) ([]LlmCall, error) {
	rows, err := q.db.Query(ctx, listLLMCallsByAttempt, evaluationAttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmCall
	for rows.Next() {
		var i LlmCall
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationAttemptID,
			&i.CorrelationID,
			&i.Model,
			&i.TokensIn,
			&i.TokensOut,
			&i.CachedTokens,
			&i.ThinkingTokens,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
