// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EvaluationAttemptStatus string

const (
	EvaluationAttemptStatusPending   EvaluationAttemptStatus = "pending"
	EvaluationAttemptStatusRunning   EvaluationAttemptStatus = "running"
	EvaluationAttemptStatusSucceeded EvaluationAttemptStatus = "succeeded"
	EvaluationAttemptStatusFailed    EvaluationAttemptStatus = "failed"
)

func (e *EvaluationAttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvaluationAttemptStatus(s)
	case string:
		*e = EvaluationAttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EvaluationAttemptStatus: %T", src)
	}
	return nil
}

type NullEvaluationAttemptStatus struct {
	EvaluationAttemptStatus EvaluationAttemptStatus
	Valid                   bool // Valid is true if EvaluationAttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvaluationAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EvaluationAttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvaluationAttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvaluationAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvaluationAttemptStatus), nil
}

func (e EvaluationAttemptStatus) Valid() bool {
	switch e {
	case EvaluationAttemptStatusPending,
		EvaluationAttemptStatusRunning,
		EvaluationAttemptStatusSucceeded,
		EvaluationAttemptStatusFailed:
		return true
	}
	return false
}

func AllEvaluationAttemptStatusValues() []EvaluationAttemptStatus {
	return []EvaluationAttemptStatus{
		EvaluationAttemptStatusPending,
		EvaluationAttemptStatusRunning,
		EvaluationAttemptStatusSucceeded,
		EvaluationAttemptStatusFailed,
	}
}

type EvaluationPurpose string

const (
	EvaluationPurposeScoring    EvaluationPurpose = "scoring"
	EvaluationPurposeExperiment EvaluationPurpose = "experiment"
)

func (e *EvaluationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvaluationPurpose(s)
	case string:
		*e = EvaluationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for EvaluationPurpose: %T", src)
	}
	return nil
}

type NullEvaluationPurpose struct {
	EvaluationPurpose EvaluationPurpose
	Valid             bool // Valid is true if EvaluationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvaluationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.EvaluationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvaluationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvaluationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvaluationPurpose), nil
}

func (e EvaluationPurpose) Valid() bool {
	switch e {
	case EvaluationPurposeScoring,
		EvaluationPurposeExperiment:
		return true
	}
	return false
}

func AllEvaluationPurposeValues() []EvaluationPurpose {
	return []EvaluationPurpose{
		EvaluationPurposeScoring,
		EvaluationPurposeExperiment,
	}
}

type QuestionType string

const (
	QuestionTypeMcq          QuestionType = "mcq"
	QuestionTypeTrueFalse    QuestionType = "true_false"
	QuestionTypeNumeric      QuestionType = "numeric"
	QuestionTypeFillIn       QuestionType = "fill_in"
	QuestionTypeOpenResponse QuestionType = "open_response"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType
	Valid        bool // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

func (e QuestionType) Valid() bool {
	switch e {
	case QuestionTypeMcq,
		QuestionTypeTrueFalse,
		QuestionTypeNumeric,
		QuestionTypeFillIn,
		QuestionTypeOpenResponse:
		return true
	}
	return false
}

func AllQuestionTypeValues() []QuestionType {
	return []QuestionType{
		QuestionTypeMcq,
		QuestionTypeTrueFalse,
		QuestionTypeNumeric,
		QuestionTypeFillIn,
		QuestionTypeOpenResponse,
	}
}

type Answer struct {
	ID           uuid.UUID
	SubmissionID uuid.UUID
	QuestionID   uuid.UUID
	RawAnswer    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Class struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ClassSubject struct {
	ClassID   uuid.UUID
	SubjectID uuid.UUID
	CreatedAt time.Time
}

type Evaluation struct {
	ID                  uuid.UUID
	EvaluationAttemptID uuid.UUID
	RawScore            pgtype.Numeric
	Marks               pgtype.Numeric
	Feedback            string
	Breakdown           []byte
	CreatedAt           time.Time
}

type EvaluationAttempt struct {
	ID        uuid.UUID
	AnswerID  uuid.UUID
	Status    EvaluationAttemptStatus
	Purpose   EvaluationPurpose
	Error     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Exam struct {
	ID        uuid.UUID
	ClassID   uuid.UUID
	Label     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ExamSubject struct {
	ID        uuid.UUID
	ExamID    uuid.UUID
	SubjectID uuid.UUID
	CreatedAt time.Time
}

type LlmCall struct {
	ID                  uuid.UUID
	EvaluationAttemptID uuid.UUID
	CorrelationID       uuid.UUID
	Model               string
	TokensIn            int32
	TokensOut           int32
	CachedTokens        *int32
	ThinkingTokens      *int32
	LatencyMs           int32
	CreatedAt           time.Time
}

type Question struct {
	ID            uuid.UUID
	ExamSubjectID uuid.UUID
	Type          QuestionType
	Config        []byte
	SchemaVersion int32
	MaximumMarks  pgtype.Numeric
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Student struct {
	ID         uuid.UUID
	ClassID    uuid.UUID
	Name       string
	RollNumber string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Subject struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
}

type Submission struct {
	ID            uuid.UUID
	ExamSubjectID uuid.UUID
	StudentID     uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	Verified     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
