// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: questions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (exam_subject_id, type, config, schema_version, maximum_marks)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at
`

type CreateQuestionParams struct {
	ExamSubjectID uuid.UUID
	Type          QuestionType
	Config        []byte
	SchemaVersion int32
	MaximumMarks  pgtype.Numeric
}

// CreateQuestion
//
//	INSERT INTO questions (exam_subject_id, type, config, schema_version, maximum_marks)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ExamSubjectID,
		arg.Type,
		arg.Config,
		arg.SchemaVersion,
		arg.MaximumMarks,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamSubjectID,
		&i.Type,
		&i.Config,
		&i.SchemaVersion,
		&i.MaximumMarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

// DeleteQuestion
//
//	DELETE FROM questions WHERE id = $1
func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at FROM questions WHERE id = $1
`

// GetQuestionByID
//
//	SELECT id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at FROM questions WHERE id = $1
func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamSubjectID,
		&i.Type,
		&i.Config,
		&i.SchemaVersion,
		&i.MaximumMarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestionsByExamSubject = `-- name: ListQuestionsByExamSubject :many
SELECT id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at FROM questions WHERE exam_subject_id = $1 ORDER BY created_at
`

// ListQuestionsByExamSubject
//
//	SELECT id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at FROM questions WHERE exam_subject_id = $1 ORDER BY created_at
func (q *Queries) ListQuestionsByExamSubject(ctx context.Context, examSubjectID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByExamSubject, examSubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.ExamSubjectID,
			&i.Type,
			&i.Config,
			&i.SchemaVersion,
			&i.MaximumMarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET type = $2, config = $3, schema_version = $4, maximum_marks = $5, updated_at = now()
WHERE id = $1
RETURNING id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID
	Type          QuestionType
	Config        []byte
	SchemaVersion int32
	MaximumMarks  pgtype.Numeric
}

// UpdateQuestion
//
//	UPDATE questions
//	SET type = $2, config = $3, schema_version = $4, maximum_marks = $5, updated_at = now()
//	WHERE id = $1
//	RETURNING id, exam_subject_id, type, config, schema_version, maximum_marks, created_at, updated_at
func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Type,
		arg.Config,
		arg.SchemaVersion,
		arg.MaximumMarks,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.ExamSubjectID,
		&i.Type,
		&i.Config,
		&i.SchemaVersion,
		&i.MaximumMarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
