// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: students.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (class_id, name, roll_number)
VALUES ($1, $2, $3)
RETURNING id, class_id, name, roll_number, created_at, updated_at
`

type CreateStudentParams struct {
	ClassID    uuid.UUID
	Name       string
	RollNumber string
}

// CreateStudent
//
//	INSERT INTO students (class_id, name, roll_number)
//	VALUES ($1, $2, $3)
//	RETURNING id, class_id, name, roll_number, created_at, updated_at
func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.ClassID, arg.Name, arg.RollNumber)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Name,
		&i.RollNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students WHERE id = $1
`

// DeleteStudent
//
//	DELETE FROM students WHERE id = $1
func (q *Queries) DeleteStudent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, class_id, name, roll_number, created_at, updated_at FROM students WHERE id = $1
`

// GetStudentByID
//
//	SELECT id, class_id, name, roll_number, created_at, updated_at FROM students WHERE id = $1
func (q *Queries) GetStudentByID(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Name,
		&i.RollNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentsByClass = `-- name: ListStudentsByClass :many
SELECT id, class_id, name, roll_number, created_at, updated_at FROM students WHERE class_id = $1 ORDER BY roll_number
`

// ListStudentsByClass
//
//	SELECT id, class_id, name, roll_number, created_at, updated_at FROM students WHERE class_id = $1 ORDER BY roll_number
func (q *Queries) ListStudentsByClass(ctx context.Context, classID uuid.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Name,
			&i.RollNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET name = $2, roll_number = $3, updated_at = now() WHERE id = $1
RETURNING id, class_id, name, roll_number, created_at, updated_at
`

type UpdateStudentParams struct {
	ID         uuid.UUID
	Name       string
	RollNumber string
}

// UpdateStudent
//
//	UPDATE students SET name = $2, roll_number = $3, updated_at = now() WHERE id = $1
//	RETURNING id, class_id, name, roll_number, created_at, updated_at
func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent, arg.ID, arg.Name, arg.RollNumber)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Name,
		&i.RollNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
