// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const bulkCreateSubjects = `-- name: BulkCreateSubjects :many
INSERT INTO subjects (name, owner_id)
SELECT DISTINCT n, $1::uuid FROM unnest($2::text[]) AS n
ON CONFLICT (owner_id, name) DO NOTHING
RETURNING id, name, owner_id, created_at
`

// Idempotent by (owner_id, name): names the owner already has are skipped
// rather than rejected (see api/services/subjects.yaml :bulk-create).
//
//	INSERT INTO subjects (name, owner_id)
//	SELECT DISTINCT n, $1::uuid FROM unnest($2::text[]) AS n
//	ON CONFLICT (owner_id, name) DO NOTHING
//	RETURNING id, name, owner_id, created_at
func (q *Queries) BulkCreateSubjects(ctx context.Context, ownerID uuid.UUID, names []string) ([]Subject, error) {
	rows, err := q.db.Query(ctx, bulkCreateSubjects, ownerID, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOwnedSubjectsByIDs = `-- name: CountOwnedSubjectsByIDs :one
SELECT count(*) FROM subjects WHERE owner_id = $1 AND id = ANY($2::uuid[])
`

// CountOwnedSubjectsByIDs
//
//	SELECT count(*) FROM subjects WHERE owner_id = $1 AND id = ANY($2::uuid[])
func (q *Queries) CountOwnedSubjectsByIDs(ctx context.Context, ownerID uuid.UUID, ids []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedSubjectsByIDs, ownerID, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

// CreateSubject
//
//	INSERT INTO subjects (name, owner_id)
//	VALUES ($1, $2)
//	RETURNING id, name, owner_id, created_at
func (q *Queries) CreateSubject(ctx context.Context, name string, ownerID uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, name, ownerID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

// DeleteSubject
//
//	DELETE FROM subjects WHERE id = $1
func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, owner_id, created_at FROM subjects WHERE id = $1
`

// GetSubjectByID
//
//	SELECT id, name, owner_id, created_at FROM subjects WHERE id = $1
func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listSubjectsByOwner = `-- name: ListSubjectsByOwner :many
SELECT id, name, owner_id, created_at FROM subjects WHERE owner_id = $1 ORDER BY name
`

// ListSubjectsByOwner
//
//	SELECT id, name, owner_id, created_at FROM subjects WHERE owner_id = $1 ORDER BY name
func (q *Queries) ListSubjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects SET name = $2 WHERE id = $1
RETURNING id, name, owner_id, created_at
`

// UpdateSubject
//
//	UPDATE subjects SET name = $2 WHERE id = $1
//	RETURNING id, name, owner_id, created_at
func (q *Queries) UpdateSubject(ctx context.Context, iD uuid.UUID, name string) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject, iD, name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
