// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, created_at FROM subjects WHERE id = $1
`

// GetSubjectByID
//
//	SELECT id, name, created_at FROM subjects WHERE id = $1
func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, created_at FROM subjects ORDER BY name
`

// ListSubjects
//
//	SELECT id, name, created_at FROM subjects ORDER BY name
func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
