// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

// CreateSubject
//
//	INSERT INTO subjects (name, owner_id)
//	VALUES ($1, $2)
//	RETURNING id, name, owner_id, created_at
func (q *Queries) CreateSubject(ctx context.Context, name string, ownerID uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, name, ownerID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, owner_id, created_at FROM subjects WHERE id = $1
`

// GetSubjectByID
//
//	SELECT id, name, owner_id, created_at FROM subjects WHERE id = $1
func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listSubjectsByOwner = `-- name: ListSubjectsByOwner :many
SELECT id, name, owner_id, created_at FROM subjects WHERE owner_id = $1 ORDER BY name
`

// ListSubjectsByOwner
//
//	SELECT id, name, owner_id, created_at FROM subjects WHERE owner_id = $1 ORDER BY name
func (q *Queries) ListSubjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
