// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, exam_subject_id, student_id, created_at, updated_at FROM submissions WHERE id = $1
`

// GetSubmissionByID
//
//	SELECT id, exam_subject_id, student_id, created_at, updated_at FROM submissions WHERE id = $1
func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ExamSubjectID,
		&i.StudentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissionsByExamSubject = `-- name: ListSubmissionsByExamSubject :many
SELECT id, exam_subject_id, student_id, created_at, updated_at FROM submissions WHERE exam_subject_id = $1 ORDER BY created_at
`

// ListSubmissionsByExamSubject
//
//	SELECT id, exam_subject_id, student_id, created_at, updated_at FROM submissions WHERE exam_subject_id = $1 ORDER BY created_at
func (q *Queries) ListSubmissionsByExamSubject(ctx context.Context, examSubjectID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByExamSubject, examSubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ExamSubjectID,
			&i.StudentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubmission = `-- name: UpsertSubmission :one
INSERT INTO submissions (exam_subject_id, student_id)
VALUES ($1, $2)
ON CONFLICT (exam_subject_id, student_id) DO UPDATE SET exam_subject_id = EXCLUDED.exam_subject_id
RETURNING id, exam_subject_id, student_id, created_at, updated_at
`

// UpsertSubmission
//
//	INSERT INTO submissions (exam_subject_id, student_id)
//	VALUES ($1, $2)
//	ON CONFLICT (exam_subject_id, student_id) DO UPDATE SET exam_subject_id = EXCLUDED.exam_subject_id
//	RETURNING id, exam_subject_id, student_id, created_at, updated_at
func (q *Queries) UpsertSubmission(ctx context.Context, examSubjectID uuid.UUID, studentID uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, upsertSubmission, examSubjectID, studentID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ExamSubjectID,
		&i.StudentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
